### ISSUE TITLE
No longer working with Google Music

### ISSUE THREAD

**Issue by AfterSpencer** [nickblt/cloudplayer-growler#1]
It seems that this plugin is no longer working with Google Music since it changed to 'Play'.

**Comment by nickblt** [comment]
Thanks for the note, I have an update "pending review" in the chrome web store. Once google approves it we should be running again.

**Comment by nickblt** [comment]
FYI google just approved the update, sorry it took so long!

**Comment by AfterSpencer** [comment]
Not a problem, thanks for the update.

It still doesn't seem to be working for me for some reason. Any suggestions?

**Comment by nickblt** [comment]
go to chrome://settings/extensions and make sure Growl Notifier for Google Play1.2.2 is listed, version 1.2.2 is important, if it isn't click update extensions now.

Other than that, make sure google play has been refreshed since the plugin has been upgraded.

If none of that works, try removing it and reinstalling it from https://chrome.google.com/webstore/detail/ojfooeehijnknikclfimbcekmncgabmp
